public class Solution {
    public char FindTheDifference(string s, string t) {
        Dictionary<char,int>charSet = new Dictionary<char,int>();

        foreach(char ch in s){
            if(!charSet.ContainsKey(ch)) charSet[ch] = 0;
            charSet[ch]++;
        }
        foreach(char ch in t){
            if(!charSet.ContainsKey(ch)) charSet[ch] =0;
            charSet[ch]--;

            if (charSet[ch] < 0) return ch;
        }
        return '\0';
    }
}

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:

// Input: s = "", t = "y"
// Output: "y"

